# Generated by Django 3.1.6 on 2021-05-08 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='create_ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='タイトル')),
                ('element', models.CharField(max_length=8, verbose_name='要素')),
                ('description', models.TextField(verbose_name='説明')),
                ('coment_count', models.IntegerField(default=0, verbose_name='コメント数')),
                ('post_count', models.IntegerField(default=0, verbose_name='参加数')),
                ('ranking_updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('int_or_float', models.BooleanField(default=True, verbose_name='小数値を適用')),
                ('up_or_down', models.BooleanField(default=False, verbose_name='昇順にする。')),
                ('max_number', models.IntegerField(default=1000000, verbose_name='最大値')),
                ('min_number', models.IntegerField(default=0, verbose_name='最小値')),
                ('Done_ranking', models.BooleanField(default=False, verbose_name='1000到達')),
                ('Createduser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Createduser', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Post_rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_name', models.CharField(max_length=50, verbose_name='投稿者')),
                ('Post_element', models.FloatField(verbose_name='要素')),
                ('Post_juni', models.IntegerField(default=0, verbose_name='順位')),
                ('Post_hensati', models.FloatField(default=50, verbose_name='偏差値')),
                ('Posteduser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Posteduser', to=settings.AUTH_USER_MODEL, verbose_name='投稿ユーザー')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posts', to='ranking.create_ranking')),
            ],
        ),
        migrations.CreateModel(
            name='Post_coment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_coment_name', models.CharField(max_length=50, verbose_name='投稿者')),
                ('Post_coment_text', models.TextField(max_length=300, verbose_name='コメント')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posts_coment', to='ranking.create_ranking')),
            ],
        ),
    ]
